# Generated by Django 5.1.3 on 2024-12-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('volatility', models.FloatField()),
                ('beta', models.FloatField()),
                ('sector', models.CharField(max_length=10)),
                ('groups', models.ManyToManyField(related_name='stocks', to='my_app.stock_group')),
            ],
        ),
    ]
