# Generated by Django 5.1.7 on 2025-03-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_stock_beta_remove_stock_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('drag_percentage', models.FloatField(default=0)),
                ('rebalance_frequency', models.CharField(choices=[('Yearly', 'Yearly'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly')], default='Yearly', max_length=10)),
                ('total_return', models.BooleanField(default=False)),
                ('rebalance_bands', models.BooleanField(default=False)),
                ('ticker', models.FloatField()),
                ('allocation', models.FloatField()),
            ],
        ),
    ]
