# Generated by Django 5.1.7 on 2025-04-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='allocation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='ticker',
            field=models.CharField(max_length=100),
        ),
    ]
